name: Build Blink

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string

env:
  zig_version: 0.14.0
  blink_version: 98146fd2318c37aca8fc3aac746cdc351c225ce9
  blink_distribution: ${{ inputs.distribution || 'full' }}
  blink_mode: ${{ inputs.distribution != 'full' && inputs.distribution || '' }}

jobs:
  build_linux:
    name: Build Linux ${{ matrix.arch }} ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64, riscv64, s390x, powerpc64le]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.zig_version }}

      - name: Install interpreters
        run: |
          sudo apt update
          sudo apt -y install qemu-user-static

      - name: Build Blink
        run: |
          export CC="${{ github.workspace }}/zigshim/zig cc -target ${{ matrix.arch }}-linux-musl"

          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure MODE=${{ env.blink_mode }} ${{ (matrix.arch != 'x86_64' && matrix.arch != 'aarch64') && '--disable-jit' || '' }}
          make -j4
          cp o/${{ env.blink_mode }}/blink/blink ${{ github.workspace }}/blink-${{ env.blink_distribution }}-linux-${{ matrix.arch }}
          cp o/${{ env.blink_mode }}/blink/blinkenlights ${{ github.workspace }}/blinkenlights-${{ env.blink_distribution }}-linux-${{ matrix.arch }}

      - name: Check Blink
        continue-on-error: true
        run: |
          cd blink
          make check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-${{ env.blink_distribution }}-linux-${{ matrix.arch }}
          path: blink-${{ env.blink_distribution }}-linux-${{ matrix.arch }}

      - name: Upload Blinkenlights
        uses: actions/upload-artifact@v4
        with:
          name: blinkenlights-${{ env.blink_distribution }}-linux-${{ matrix.arch }}
          path: blinkenlights-${{ env.blink_distribution }}-linux-${{ matrix.arch }}

  build_openbsd:
    name: Build OpenBSD ${{ matrix.os_version }} ${{ matrix.arch }} ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["7.6"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/openbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg_add git gmake

      - name: Build Blink
        shell: openbsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure MODE=${{ env.blink_mode }} --disable-jit
          gmake -j4
          cp o/${{ env.blink_mode }}/blink/blink ${{ github.workspace }}/blink-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}
          cp o/${{ env.blink_mode }}/blink/blinkenlights ${{ github.workspace }}/blinkenlights-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        continue-on-error: true
        shell: openbsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Upload Blinkenlights
        uses: actions/upload-artifact@v4
        with:
          name: blinkenlights-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blinkenlights-${{ env.blink_distribution }}-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_netbsd:
    name: Build NetBSD ${{ matrix.os_version }} ${{ matrix.arch }} ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["10.0", "10.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/netbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            /usr/sbin/pkg_add git gmake

      - name: Build Blink
        shell: netbsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          bash ./configure MODE=${{ env.blink_mode }}
          gmake -j4
          /usr/sbin/paxctl +m o/${{ env.blink_mode }}/blink/blink
          /usr/sbin/paxctl +m o/${{ env.blink_mode }}/blink/blinkenlights
          cp o/${{ env.blink_mode }}/blink/blink ${{ github.workspace }}/blink-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}
          cp o/${{ env.blink_mode }}/blink/blinkenlights ${{ github.workspace }}/blinkenlights-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        continue-on-error: true
        shell: netbsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Upload Blinkenlights
        uses: actions/upload-artifact@v4
        with:
          name: blinkenlights-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blinkenlights-${{ env.blink_distribution }}-netbsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_freebsd:
    name: Build FreeBSD ${{ matrix.os_version }} ${{ matrix.arch }} ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["14.2", "15.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/freebsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg install -y git gmake

      - name: Build Blink
        shell: freebsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure MODE=${{ env.blink_mode }}
          gmake -j4
          cp o/${{ env.blink_mode }}/blink/blink ${{ github.workspace }}/blink-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}
          cp o/${{ env.blink_mode }}/blink/blinkenlights ${{ github.workspace }}/blinkenlights-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        continue-on-error: true
        shell: freebsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Upload Blinkenlights
        uses: actions/upload-artifact@v4
        with:
          name: blinkenlights-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blinkenlights-${{ env.blink_distribution }}-freebsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_solaris:
    name: Build Solaris ${{ matrix.os_version }} ${{ matrix.arch }} ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        os_version: ["11.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/solaris-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg install --accept git gcc

      - name: Build Blink
        shell: solaris {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          CC=gcc bash ./configure MODE=${{ env.blink_mode }}
          gmake -j4
          cp o/${{ env.blink_mode }}/blink/blink ${{ github.workspace }}/blink-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}
          cp o/${{ env.blink_mode }}/blink/blinkenlights ${{ github.workspace }}/blinkenlights-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        continue-on-error: true
        shell: solaris {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Upload Blinkenlights
        uses: actions/upload-artifact@v4
        with:
          name: blinkenlights-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}
          path: blinkenlights-${{ env.blink_distribution }}-solaris${{ matrix.os_version }}-${{ matrix.arch }}