name: Build Blink

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:

env:
  zig_version: 0.13.0
  blink_version: 4da95da865a1d3ccdc2e802cccfbddd8507d1c95

jobs:
  build_openbsd:
    name: Build OpenBSD ${{ matrix.os_version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: [7.6, 7.5]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/openbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg_add cmake gmake git

      - name: Build Blink
        shell: openbsd {0}
        run: |
          cd ${{ github.workspace }}
          git config --global --add safe.directory ${{ github.workspace}}/blink
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure
          gmake -j4
          cp o/blink/blink blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: ./blink/blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}