name: Build Blink matrix

on:
  workflow_dispatch:

jobs:
  build_matrix:
    name: Build Blink matrix
    strategy:
      fail-fast: false
      matrix:
        distribution: [ tiny, full ]