name: Build Blink matrix

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_matrix:
    name: Build Blink matrix
    strategy:
      fail-fast: false
      matrix:
        distribution: [ tiny, full ]
    uses: ./.github/workflows/build.yml
    with:
      distribution: ${{ matrix.distribution }}