name: Build Blink

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:

env:
  zig_version: 0.13.0
  blink_version: eb99c60e950cd6d7b9e6f1aedeb95ef2690390b5

jobs:
  build_openbsd:
    name: Build OpenBSD ${{ matrix.os_version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["7.6"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/openbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg_add git gmake

      - name: Build Blink
        shell: openbsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure
          gmake -j4
          cp o/blink/blink ${{ github.workspace }}/blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        shell: openbsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-openbsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_netbsd:
    name: Build NetBSD ${{ matrix.os_version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["10.0", "10.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/netbsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            /usr/sbin/pkg_add git gmake

      - name: Build Blink
        shell: netbsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          bash ./configure
          gmake -j4
          /usr/sbin/paxctl +m o/blink/blink
          cp o/blink/blink ${{ github.workspace }}/blink-netbsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        shell: netbsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-netbsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-netbsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_freebsd:
    name: Build FreeBSD ${{ matrix.os_version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        os_version: ["14.2", "15.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/freebsd-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg install -y git gmake

      - name: Build Blink
        shell: freebsd {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          ./configure
          gmake -j4
          cp o/blink/blink ${{ github.workspace }}/blink-freebsd${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        shell: freebsd {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-freebsd${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-freebsd${{ matrix.os_version }}-${{ matrix.arch }}

  build_solaris:
    name: Build Solaris ${{ matrix.os_version }} ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        os_version: ["11.4"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start VM
        uses: vmactions/solaris-vm@v1
        with:
          sync: nfs
          arch: ${{ matrix.arch }}
          release: ${{ matrix.os_version }}
          prepare: |
            pkg install --accept git gcc

      - name: Build Blink
        shell: solaris {0}
        run: |
          git clone https://github.com/bjia56/blink.git
          cd blink
          git checkout ${{ env.blink_version }}
          CC=gcc ./configure
          gmake -j4
          cp o/blink/blink ${{ github.workspace }}/blink-solaris${{ matrix.os_version }}-${{ matrix.arch }}

      - name: Check Blink
        shell: solaris {0}
        run: |
          cd blink
          gmake check

      - name: Upload Blink
        uses: actions/upload-artifact@v4
        with:
          name: blink-solaris${{ matrix.os_version }}-${{ matrix.arch }}
          path: blink-solaris${{ matrix.os_version }}-${{ matrix.arch }}